package cmd

import (
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/akhilesharora/pqc-testkit/pkg/algorithms"
	"github.com/spf13/cobra"
)

var (
	genVecAlgo   string
	genVecOutput string
	genVecCount  int
)

var genvecCmd = &cobra.Command{
	Use:   "gen-vectors",
	Short: "Generate KAT test vectors from software reference implementations",
	Long: `Generates Known Answer Test vectors by running the software reference
implementations (Go stdlib for ML-KEM, circl for ML-DSA/SLH-DSA) and
recording all inputs and outputs in NIST .rsp format.

These vectors can then be used to validate FPGA hardware implementations
using the kat command.`,
	RunE: runGenVec,
}

func init() {
	genvecCmd.Flags().StringVarP(&genVecAlgo, "algorithm", "a", "ml-kem", "algorithm (ml-kem, ml-dsa, slh-dsa)")
	genvecCmd.Flags().StringVarP(&genVecOutput, "output", "o", "vectors/", "output directory")
	genvecCmd.Flags().IntVarP(&genVecCount, "count", "n", 10, "number of test vectors to generate")
	rootCmd.AddCommand(genvecCmd)
}

func runGenVec(cmd *cobra.Command, args []string) error {
	algo := strings.ToLower(genVecAlgo)
	suite, err := algorithms.NewSuite(algo)
	if err != nil {
		return err
	}

	fmt.Printf("PQC Test Kit - Vector Generation\n")
	fmt.Printf("Algorithm: %s\n", suite.Name())
	fmt.Printf("Count:     %d vectors per level\n\n", genVecCount)

	for _, level := range suite.Levels() {
		subdir := filepath.Join(genVecOutput, algo)
		if err := os.MkdirAll(subdir, 0755); err != nil {
			return fmt.Errorf("creating directory %s: %w", subdir, err)
		}

		filename := fmt.Sprintf("%s-%d.rsp", strings.ToUpper(algo), level)
		path := filepath.Join(subdir, filename)

		f, err := os.Create(path)
		if err != nil {
			return fmt.Errorf("creating %s: %w", path, err)
		}

		fmt.Fprintf(f, "# %s level %d KAT vectors\n", suite.Name(), level)
		fmt.Fprintf(f, "# Generated by pqc-testkit gen-vectors\n\n")

		switch s := suite.(type) {
		case algorithms.KEMSuite:
			for i := 0; i < genVecCount; i++ {
				pk, sk, err := s.KeyGen(level)
				if err != nil {
					f.Close()
					return fmt.Errorf("keygen vector %d: %w", i, err)
				}

				ct, ss, err := s.Encapsulate(level, pk)
				if err != nil {
					f.Close()
					return fmt.Errorf("encaps vector %d: %w", i, err)
				}

				fmt.Fprintf(f, "count = %d\n", i)
				fmt.Fprintf(f, "pk = %s\n", hex.EncodeToString(pk))
				fmt.Fprintf(f, "sk = %s\n", hex.EncodeToString(sk))
				fmt.Fprintf(f, "ct = %s\n", hex.EncodeToString(ct))
				fmt.Fprintf(f, "ss = %s\n\n", hex.EncodeToString(ss))
			}

		case algorithms.SignSuite:
			msg := []byte("pqc-testkit KAT vector generation test message")
			for i := 0; i < genVecCount; i++ {
				pk, sk, err := s.KeyGen(level)
				if err != nil {
					f.Close()
					return fmt.Errorf("keygen vector %d: %w", i, err)
				}

				sig, err := s.Sign(level, sk, msg)
				if err != nil {
					f.Close()
					return fmt.Errorf("sign vector %d: %w", i, err)
				}

				fmt.Fprintf(f, "count = %d\n", i)
				fmt.Fprintf(f, "pk = %s\n", hex.EncodeToString(pk))
				fmt.Fprintf(f, "sk = %s\n", hex.EncodeToString(sk))
				fmt.Fprintf(f, "msg = %s\n", hex.EncodeToString(msg))
				fmt.Fprintf(f, "sig = %s\n\n", hex.EncodeToString(sig))
			}
		}

		f.Close()
		fmt.Printf("  Level %d: %s (%d vectors)\n", level, path, genVecCount)
	}

	fmt.Printf("\nDone. Validate with: ./pqc-testkit kat -a %s -v %s\n", algo, genVecOutput)
	return nil
}
