// mlkem_ctrl.sv - ML-KEM microcode sequencer
//
// Executes the FIPS 203 programs stored in mlkem_ucode_rom (generated by
// scripts/gen_mlkem_ucode.py). Every instruction moves real data between
// the data buffer (host I/O + scratch), the Keccak sponge and the
// polynomial units:
//
//   HINIT/HABS/HABI/HFIN/HSQZ  buffer <-> keccak_sponge (G, H, J, PRF, XOF)
//   COPY / CMP / CSEL          buffer word moves, FO re-encryption check,
//                              constant-time implicit-rejection select
//   SAMPLE / CBD / DECODE      sponge or buffer -> mlkem_unpack -> poly RAM
//   ENCODE                     poly RAM -> mlkem_pack -> buffer
//   NTT/INTT/BMUL/ADD/SUB      mlkem_poly_alu on poly RAM
//
// Buffer operands of HABS / HSQZ / COPY / CMP / CSEL / DECODE are 32-bit
// word aligned with lengths that are multiples of 4 (DECODE: of 8)
// (gen_mlkem_ucode.py asserts this), so the buffer is accessed one word per
// cycle. Port B commands are registered and the buffer has output
// registers, so read data arrives 3 cycles after the read is decided. A
// read stream feeds a 6-entry word FIFO:
//   HABS          one word (4 bytes) per cycle into the sponge
//   DECODE        two words (one 64-bit chunk) per take into the unpacker
//   CMP           a / b words interleaved, compared in pairs
//   COPY, CSEL    one word written per FIFO word (writes win over reads)
//   HSQZ          one squeezed word written per cycle
//   ENCODE        mlkem_pack emits whole words
//
// Error codes (ERROR_CODE register):
//   1 = unsupported SEC_LEVEL or OP_MODE (the core implements ML-KEM-768
//       only: SEC_LEVEL must be 768)
//   2 = encapsulation key failed the FIPS 203 modulus check
//   3 = illegal microcode instruction

module mlkem_ctrl (
    input  logic        clk,
    input  logic        rst_n,

    // CSR interface.
    input  logic        ctrl_start,
    input  logic        ctrl_reset,
    input  logic [31:0] sec_level,
    input  logic [31:0] op_mode,
    input  logic [31:0] data_in_addr,
    input  logic [31:0] data_out_addr,
    output logic        status_busy,
    output logic        status_done,
    output logic        status_error,
    output logic [31:0] error_code,
    output logic [31:0] cycle_count,

    // Data buffer port B (registered commands; read latency 2).
    output logic        buf_en,
    output logic [3:0]  buf_we,
    output logic [10:0] buf_addr,
    output logic [31:0] buf_din,
    input  logic [31:0] buf_dout,

    // Sponge.
    output logic        h_init,
    output logic [1:0]  h_mode,
    input  logic        h_idle,
    output logic        h_absorb_valid,
    output logic [63:0] h_absorb_data,
    output logic [3:0]  h_absorb_n,
    input  logic        h_absorb_ready,
    output logic        h_finalize,
    input  logic        h_squeeze_valid,
    input  logic [63:0] h_squeeze_data,
    input  logic [3:0]  h_squeeze_avail,
    output logic        h_squeeze_take,
    output logic [3:0]  h_squeeze_n,

    // Polynomial ALU.
    output logic        alu_start,
    output logic [2:0]  alu_op,
    output logic [2:0]  alu_sa,
    output logic [2:0]  alu_sb,
    output logic [2:0]  alu_sc,
    output logic        alu_acc,
    input  logic        alu_done,

    // Unpacker.
    output logic        up_start,
    output logic [1:0]  up_mode,
    output logic [3:0]  up_param,
    output logic        up_check,
    output logic [2:0]  up_slot,
    input  logic        up_done,
    input  logic [1:0]  up_range_err,
    output logic        up_src_valid,
    output logic [63:0] up_src_data,    // One 64-bit chunk.
    input  logic        up_src_take,

    // Packer.
    output logic        pk_start,
    output logic [3:0]  pk_d,
    output logic [2:0]  pk_slot,
    input  logic        pk_done,
    input  logic        pk_out_valid,
    input  logic [31:0] pk_out_word,

    // Poly RAM owner: 0 = ALU, 1 = unpacker, 2 = packer.
    output logic [1:0]  pr_sel,

    // Synchronous abort for all datapath units.
    output logic        units_clr
);

    // Registered active-high synchronous reset, local to this module
    // (replicated by fanout; no inverter on the high-fanout net).
    (* max_fanout = 32 *) logic srst;
    always_ff @(posedge clk)
        srst <= !rst_n;

    // Opcodes (see scripts/gen_mlkem_ucode.py).
    localparam logic [7:0] OP_END    = 8'h00;
    localparam logic [7:0] OP_HINIT  = 8'h01;
    localparam logic [7:0] OP_HABS   = 8'h02;
    localparam logic [7:0] OP_HABI   = 8'h03;
    localparam logic [7:0] OP_HFIN   = 8'h04;
    localparam logic [7:0] OP_HSQZ   = 8'h05;
    localparam logic [7:0] OP_COPY   = 8'h06;
    localparam logic [7:0] OP_CMP    = 8'h07;
    localparam logic [7:0] OP_CSEL   = 8'h08;
    localparam logic [7:0] OP_SAMPLE = 8'h10;
    localparam logic [7:0] OP_CBD    = 8'h11;
    localparam logic [7:0] OP_DECODE = 8'h12;
    localparam logic [7:0] OP_ENCODE = 8'h13;
    localparam logic [7:0] OP_NTT    = 8'h20;
    localparam logic [7:0] OP_INTT   = 8'h21;
    localparam logic [7:0] OP_BMUL   = 8'h22;
    localparam logic [7:0] OP_ADD    = 8'h23;
    localparam logic [7:0] OP_SUB    = 8'h24;

    localparam logic [31:0] ERR_PARAM   = 32'd1;
    localparam logic [31:0] ERR_EK      = 32'd2;
    localparam logic [31:0] ERR_ILLEGAL = 32'd3;

    typedef enum logic [3:0] {
        C_IDLE,
        C_FETCH,     // ROM address = pc.
        C_DECODE,    // ROM data valid: dispatch.
        C_HINIT,     // Wait for sponge idle, init.
        C_HABI,      // Absorb immediate byte(s).
        C_HFIN,      // Finalize.
        C_HSQZ,      // Squeeze to buffer.
        C_HABS,      // Stream buffer words into the sponge.
        C_CMP,       // Read a / b words, compare pairs.
        C_COPY,      // COPY / CSEL: read and write words.
        C_UNIT,      // Wait for poly unit.
        C_NEXT       // Advance pc.
    } state_t;

    localparam int PC_W   = 9;          // Program counter (mlkem_ucode_rom ADDR_W).
    localparam int FDEPTH = 6;          // Read FIFO entries.

    (* fsm_encoding = "one_hot" *) state_t state;
    logic [PC_W-1:0] pc;
    logic [7:0]  i_op;
    logic [7:0]  i_p;
    logic [13:0] ptr_a, ptr_b, ptr_c;   // Effective byte addresses.
    logic [15:0] len;                   // Words (HABS, HSQZ, COPY, CSEL) or pairs (CMP) left.
    logic        flag;                  // CMP mismatch (sticky per run).
    logic        ek_bad;                // Modulus-check failure (sticky per run).
    logic [13:0] in_base, out_base;
    logic [1:0]  op_idx;
    logic        unit_src_sponge;       // Unpacker fed from sponge.
    logic        is_decode, is_encode, is_csel;
    logic [15:0] imm;
    logic        lvl_ok, op_ok;         // Registered parameter checks.
    logic        rst_q;                 // Registered ctrl_reset.

    // ---------------------------------------------------------------------
    // Microcode ROM.
    // ---------------------------------------------------------------------
    logic [95:0]     rom_data;
    logic [PC_W-1:0] rom_entry;

    mlkem_ucode_rom #(
        .ADDR_W (PC_W)
    ) u_rom (
        .clk   (clk),
        .addr  (pc),
        .data  (rom_data),
        .op    (op_idx),
        .entry (rom_entry)
    );

    logic [7:0]  f_op, f_p;
    logic [15:0] f_a, f_b, f_c, f_len;
    assign f_op  = rom_data[95:88];
    assign f_p   = rom_data[87:80];
    assign f_a   = rom_data[79:64];
    assign f_b   = rom_data[63:48];
    assign f_c   = rom_data[47:32];
    assign f_len = rom_data[31:16];

    function automatic logic [13:0] eff(input logic [15:0] t,
                                        input logic [13:0] ib,
                                        input logic [13:0] ob);
        case (t[15:14])
            2'd1:    return ib + t[13:0];
            2'd2:    return ob + t[13:0];
            default: return t[13:0];
        endcase
    endfunction

    // ---------------------------------------------------------------------
    // Read stream: registered read commands, 6-entry word FIFO.
    // A read decided in cycle D has its data in buf_dout during D+3.
    // ---------------------------------------------------------------------
    logic [31:0] fq [0:FDEPTH-1];       // fq[0] = head.
    logic [2:0]  fcnt;                  // Valid entries.
    logic [2:0]  rp;                    // Reads in flight, rp[2]: data this cycle.
    logic [15:0] rd_left;               // Reads still to issue.
    logic        rd_b;                  // Next read uses ptr_b (CMP: alternate).
    logic        rs_on;                 // State with a read stream.

    logic [1:0]  inflight;
    assign inflight = 2'(rp[0]) + 2'(rp[1]) + 2'(rp[2]);

    // FIFO consumers (pop 1 or 2 words).
    logic pop1, pop2;
    logic wr_copy, wr_sqz, wr_enc;      // Write commands this cycle.
    assign wr_copy = (state == C_COPY) && (fcnt != 3'd0);
    assign wr_sqz  = (state == C_HSQZ) && h_squeeze_valid;
    assign wr_enc  = (state == C_UNIT) && is_encode && pk_out_valid;
    assign pop1    = ((state == C_HABS) && (fcnt != 3'd0) && h_absorb_ready) || wr_copy;
    assign pop2    = ((state == C_CMP) && (fcnt >= 3'd2)) ||
                     ((state == C_UNIT) && is_decode && up_src_take);

    logic rd_issue;
    assign rd_issue = rs_on && (rd_left != 16'd0) && !wr_copy &&
                      (3'(fcnt) + 3'(inflight) < 3'(FDEPTH));

    // Profiling only (testbench/core_sim): sequencer overhead cycles.
    logic seq_overhead;
    assign seq_overhead = (state == C_NEXT) || (state == C_FETCH) || (state == C_DECODE);

    // ---------------------------------------------------------------------
    // Sponge, unit handshakes.
    // ---------------------------------------------------------------------
    assign h_init         = (state == C_HINIT) && h_idle;
    assign h_mode         = i_p[1:0];
    // HABI absorbs its 1-2 immediate bytes in one chunk (the generator keeps
    // them inside a lane); HABS one FIFO word. HSQZ squeezes a word (its
    // squeeze position is always a multiple of 4).
    assign h_absorb_valid = (state == C_HABI) || ((state == C_HABS) && (fcnt != 3'd0));
    assign h_absorb_data  = (state == C_HABI) ? {48'b0, imm} : {32'b0, fq[0]};
    assign h_absorb_n     = (state == C_HABI) ? ((i_p == 8'd1) ? 4'd1 : 4'd2) : 4'd4;
    assign h_finalize     = (state == C_HFIN) && h_absorb_ready;
    assign h_squeeze_take = wr_sqz ||
                            ((state == C_UNIT) && unit_src_sponge && up_src_take);
    assign h_squeeze_n    = (state == C_HSQZ) ? 4'd4 : 4'd8;

    // Unpacker source: sponge lanes, or two FIFO words (DECODE).
    assign up_src_valid = unit_src_sponge ? h_squeeze_valid : (fcnt >= 3'd2);
    assign up_src_data  = unit_src_sponge ? h_squeeze_data  : {fq[1], fq[0]};

    // ---------------------------------------------------------------------
    // Sequencer.
    // ---------------------------------------------------------------------
    always_ff @(posedge clk) begin                 // Synchronous reset.
        if (srst) begin
            state           <= C_IDLE;
            pc              <= '0;
            i_op            <= '0;
            i_p             <= '0;
            imm             <= '0;
            ptr_a           <= '0;
            ptr_b           <= '0;
            ptr_c           <= '0;
            len             <= '0;
            fcnt            <= '0;
            rp              <= '0;
            rd_left         <= '0;
            rd_b            <= 1'b0;
            rs_on           <= 1'b0;
            flag            <= 1'b0;
            ek_bad          <= 1'b0;
            in_base         <= '0;
            out_base        <= '0;
            op_idx          <= '0;
            unit_src_sponge <= 1'b0;
            is_decode       <= 1'b0;
            is_encode       <= 1'b0;
            is_csel         <= 1'b0;
            lvl_ok          <= 1'b0;
            op_ok           <= 1'b0;
            rst_q           <= 1'b0;
            status_busy     <= 1'b0;
            status_done     <= 1'b0;
            status_error    <= 1'b0;
            error_code      <= '0;
            cycle_count     <= '0;
            alu_start       <= 1'b0;
            alu_op          <= '0;
            alu_sa          <= '0;
            alu_sb          <= '0;
            alu_sc          <= '0;
            alu_acc         <= 1'b0;
            up_start        <= 1'b0;
            up_mode         <= '0;
            up_param        <= '0;
            up_check        <= 1'b0;
            up_slot         <= '0;
            pk_start        <= 1'b0;
            pk_d            <= '0;
            pk_slot         <= '0;
            pr_sel          <= '0;
            units_clr       <= 1'b0;
            buf_en          <= 1'b0;
            buf_we          <= '0;
        end else begin
            alu_start <= 1'b0;
            up_start  <= 1'b0;
            pk_start  <= 1'b0;
            units_clr <= 1'b0;
            lvl_ok    <= (sec_level == 32'd768);
            op_ok     <= (op_mode < 32'd3);
            rst_q     <= ctrl_reset;

            if (status_busy)
                cycle_count <= cycle_count + 32'd1;

            if (|up_range_err)
                ek_bad <= 1'b1;

            // ---- Port B command for the next cycle ----
            buf_en <= 1'b0;
            buf_we <= 4'b0000;
            if (wr_copy || wr_sqz || wr_enc) begin
                buf_en <= 1'b1;
                buf_we <= 4'b1111;
                if (wr_copy) begin
                    buf_addr <= is_csel ? ptr_c[12:2] : ptr_b[12:2];
                    buf_din  <= fq[0];
                end else if (wr_sqz) begin
                    buf_addr <= ptr_a[12:2];
                    buf_din  <= h_squeeze_data[31:0];
                end else begin
                    buf_addr <= ptr_b[12:2];
                    buf_din  <= pk_out_word;
                end
            end else if (rd_issue) begin
                buf_en   <= 1'b1;
                buf_addr <= rd_b ? ptr_b[12:2] : ptr_a[12:2];
            end

            // ---- Read stream and FIFO ----
            rp <= {rp[1:0], rd_issue && !rst_q};
            if (rd_issue) begin
                rd_left <= rd_left - 16'd1;
                if (rd_b) ptr_b <= ptr_b + 14'd4;
                else      ptr_a <= ptr_a + 14'd4;
                if (state == C_CMP)
                    rd_b <= !rd_b;
            end
            begin
                logic [2:0] np;             // Entries left after the pop.
                np = fcnt - (pop2 ? 3'd2 : pop1 ? 3'd1 : 3'd0);
                for (int i = 0; i < FDEPTH; i++) begin
                    if (pop2)
                        fq[i] <= (i + 2 < FDEPTH) ? fq[i + 2] : fq[i];
                    else if (pop1)
                        fq[i] <= (i + 1 < FDEPTH) ? fq[i + 1] : fq[i];
                end
                if (rp[2])
                    fq[np] <= buf_dout;
                fcnt <= np + 3'(rp[2]);
            end

            if (rst_q) begin
                state        <= C_IDLE;
                status_busy  <= 1'b0;
                status_done  <= 1'b0;
                status_error <= 1'b0;
                error_code   <= '0;
                cycle_count  <= '0;
                fcnt         <= '0;
                rp           <= '0;
                rs_on        <= 1'b0;
                units_clr    <= 1'b1;
            end else begin
                case (state)
                    C_IDLE: begin
                        if (ctrl_start) begin
                            status_done  <= 1'b0;
                            status_error <= 1'b0;
                            error_code   <= '0;
                            cycle_count  <= '0;
                            if (!lvl_ok || !op_ok) begin
                                status_error <= 1'b1;
                                error_code   <= ERR_PARAM;
                            end else begin
                                op_idx      <= op_mode[1:0];
                                in_base     <= data_in_addr[13:0];
                                out_base    <= data_out_addr[13:0];
                                flag        <= 1'b0;
                                ek_bad      <= 1'b0;
                                status_busy <= 1'b1;
                                state       <= C_NEXT;  // Loads pc from entry.
                                pc          <= '1;
                            end
                        end
                    end

                    C_NEXT: begin
                        pc    <= (pc == '1) ? rom_entry : pc + 1'b1;
                        state <= C_FETCH;
                    end

                    C_FETCH: state <= C_DECODE;

                    C_DECODE: begin
                        i_op      <= f_op;
                        i_p       <= f_p;
                        imm       <= f_a;
                        is_decode <= (f_op == OP_DECODE);
                        is_encode <= (f_op == OP_ENCODE);
                        is_csel   <= (f_op == OP_CSEL);
                        // CMP counts pairs and reads both operands.
                        len       <= {2'b00, f_len[15:2]};
                        rd_left   <= (f_op == OP_CMP) ? {1'b0, f_len[15:1]} : {2'b00, f_len[15:2]};
                        rd_b      <= (f_op == OP_CSEL) && flag;
                        rs_on     <= (f_op == OP_HABS || f_op == OP_CMP || f_op == OP_COPY ||
                                      f_op == OP_CSEL || f_op == OP_DECODE);
                        fcnt      <= '0;
                        ptr_a     <= eff(f_a, in_base, out_base);
                        ptr_b     <= eff(f_b, in_base, out_base);
                        ptr_c     <= eff(f_c, in_base, out_base);
                        case (f_op)
                            OP_END: begin
                                status_busy <= 1'b0;
                                status_done <= 1'b1;
                                if (ek_bad) begin
                                    status_error <= 1'b1;
                                    error_code   <= ERR_EK;
                                end
                                state <= C_IDLE;
                            end
                            OP_HINIT: state <= C_HINIT;
                            OP_HABI:  state <= C_HABI;
                            OP_HFIN:  state <= C_HFIN;
                            OP_HSQZ:  state <= state_t'((f_len == 0) ? C_NEXT : C_HSQZ);
                            OP_HABS:  state <= state_t'((f_len == 0) ? C_NEXT : C_HABS);
                            OP_CMP:   state <= state_t'((f_len == 0) ? C_NEXT : C_CMP);
                            OP_COPY, OP_CSEL:
                                      state <= state_t'((f_len == 0) ? C_NEXT : C_COPY);
                            OP_SAMPLE, OP_CBD, OP_DECODE: begin
                                up_start        <= 1'b1;
                                up_mode         <= (f_op == OP_SAMPLE) ? 2'd0 :
                                                   (f_op == OP_CBD)    ? 2'd1 : 2'd2;
                                up_param        <= f_p[3:0];
                                up_check        <= f_p[4];
                                up_slot         <= f_c[2:0];
                                unit_src_sponge <= (f_op != OP_DECODE);
                                pr_sel          <= 2'd1;
                                state           <= C_UNIT;
                            end
                            OP_ENCODE: begin
                                pk_start        <= 1'b1;
                                pk_d            <= f_p[3:0];
                                pk_slot         <= f_a[2:0];
                                unit_src_sponge <= 1'b0;
                                pr_sel          <= 2'd2;
                                state           <= C_UNIT;
                            end
                            OP_NTT, OP_INTT, OP_BMUL, OP_ADD, OP_SUB: begin
                                alu_start       <= 1'b1;
                                alu_op          <= (f_op == OP_NTT)  ? 3'd0 :
                                                   (f_op == OP_INTT) ? 3'd1 :
                                                   (f_op == OP_BMUL) ? 3'd2 :
                                                   (f_op == OP_ADD)  ? 3'd3 : 3'd4;
                                alu_sa          <= f_a[2:0];
                                alu_sb          <= f_b[2:0];
                                alu_sc          <= f_c[2:0];
                                alu_acc         <= f_p[0];
                                unit_src_sponge <= 1'b0;
                                pr_sel          <= 2'd0;
                                state           <= C_UNIT;
                            end
                            default: begin
                                status_busy  <= 1'b0;
                                status_error <= 1'b1;
                                error_code   <= ERR_ILLEGAL;
                                state        <= C_IDLE;
                            end
                        endcase
                    end

                    C_HINIT: if (h_idle) state <= C_NEXT;

                    C_HABI: if (h_absorb_ready) state <= C_NEXT;

                    C_HFIN: if (h_absorb_ready) state <= C_NEXT;

                    C_HSQZ: if (wr_sqz) begin
                        ptr_a <= ptr_a + 14'd4;
                        len   <= len - 16'd1;
                        if (len == 16'd1)
                            state <= C_NEXT;
                    end

                    C_HABS: if (pop1) begin
                        len <= len - 16'd1;
                        if (len == 16'd1) begin
                            rs_on <= 1'b0;
                            state <= C_NEXT;
                        end
                    end

                    C_CMP: if (pop2) begin
                        if (fq[0] != fq[1])
                            flag <= 1'b1;
                        len <= len - 16'd1;
                        if (len == 16'd1) begin
                            rs_on <= 1'b0;
                            state <= C_NEXT;
                        end
                    end

                    C_COPY: if (wr_copy) begin
                        if (is_csel) ptr_c <= ptr_c + 14'd4;
                        else         ptr_b <= ptr_b + 14'd4;
                        len <= len - 16'd1;
                        if (len == 16'd1) begin
                            rs_on <= 1'b0;
                            state <= C_NEXT;
                        end
                    end

                    C_UNIT: begin
                        if (wr_enc)
                            ptr_b <= ptr_b + 14'd4;
                        if (alu_done || up_done || pk_done) begin
                            rs_on <= 1'b0;
                            state <= C_NEXT;
                        end
                    end

                    default: state <= C_IDLE;
                endcase
            end
        end
    end

endmodule
