// mlkem_ctrl.sv - ML-KEM microcode sequencer
//
// Executes the FIPS 203 programs stored in mlkem_ucode_rom (generated by
// scripts/gen_mlkem_ucode.py). Every instruction moves real data between
// the data buffer (host I/O + scratch), the Keccak sponge and the
// polynomial units:
//
//   HINIT/HABS/HABI/HFIN/HSQZ  buffer <-> keccak_sponge (G, H, J, PRF, XOF)
//   COPY / CMP / CSEL          buffer byte moves, FO re-encryption check,
//                              constant-time implicit-rejection select
//   SAMPLE / CBD / DECODE      sponge or buffer -> mlkem_unpack -> poly RAM
//   ENCODE                     poly RAM -> mlkem_pack -> buffer
//   NTT/INTT/BMUL/ADD/SUB      mlkem_poly_alu on poly RAM
//
// Error codes (ERROR_CODE register):
//   1 = unsupported SEC_LEVEL or OP_MODE (the core implements ML-KEM-768
//       only: SEC_LEVEL must be 768)
//   2 = encapsulation key failed the FIPS 203 modulus check
//   3 = illegal microcode instruction

module mlkem_ctrl (
    input  logic        clk,
    input  logic        rst_n,

    // CSR interface.
    input  logic        ctrl_start,
    input  logic        ctrl_reset,
    input  logic [31:0] sec_level,
    input  logic [31:0] op_mode,
    input  logic [31:0] data_in_addr,
    input  logic [31:0] data_out_addr,
    output logic        status_busy,
    output logic        status_done,
    output logic        status_error,
    output logic [31:0] error_code,
    output logic [31:0] cycle_count,

    // Data buffer port B (byte-addressed via word + lane).
    output logic        buf_en,
    output logic [3:0]  buf_we,
    output logic [11:0] buf_addr,
    output logic [31:0] buf_din,
    input  logic [31:0] buf_dout,

    // Sponge.
    output logic        h_init,
    output logic [1:0]  h_mode,
    input  logic        h_idle,
    output logic        h_absorb_valid,
    output logic [7:0]  h_absorb_byte,
    input  logic        h_absorb_ready,
    output logic        h_finalize,
    input  logic        h_squeeze_valid,
    input  logic [7:0]  h_squeeze_byte,
    output logic        h_squeeze_take,

    // Polynomial ALU.
    output logic        alu_start,
    output logic [2:0]  alu_op,
    output logic [2:0]  alu_sa,
    output logic [2:0]  alu_sb,
    output logic [2:0]  alu_sc,
    output logic        alu_acc,
    input  logic        alu_done,

    // Unpacker.
    output logic        up_start,
    output logic [1:0]  up_mode,
    output logic [3:0]  up_param,
    output logic        up_check,
    output logic [2:0]  up_slot,
    input  logic        up_done,
    input  logic        up_range_err,
    output logic        up_src_valid,
    output logic [7:0]  up_src_byte,
    input  logic        up_src_take,

    // Packer.
    output logic        pk_start,
    output logic [3:0]  pk_d,
    output logic [2:0]  pk_slot,
    input  logic        pk_done,
    input  logic        pk_out_valid,
    input  logic [7:0]  pk_out_byte,

    // Poly RAM owner: 0 = ALU, 1 = unpacker, 2 = packer.
    output logic [1:0]  pr_sel,

    // Synchronous abort for all datapath units.
    output logic        units_clr
);

    // Opcodes (see scripts/gen_mlkem_ucode.py).
    localparam logic [7:0] OP_END    = 8'h00;
    localparam logic [7:0] OP_HINIT  = 8'h01;
    localparam logic [7:0] OP_HABS   = 8'h02;
    localparam logic [7:0] OP_HABI   = 8'h03;
    localparam logic [7:0] OP_HFIN   = 8'h04;
    localparam logic [7:0] OP_HSQZ   = 8'h05;
    localparam logic [7:0] OP_COPY   = 8'h06;
    localparam logic [7:0] OP_CMP    = 8'h07;
    localparam logic [7:0] OP_CSEL   = 8'h08;
    localparam logic [7:0] OP_SAMPLE = 8'h10;
    localparam logic [7:0] OP_CBD    = 8'h11;
    localparam logic [7:0] OP_DECODE = 8'h12;
    localparam logic [7:0] OP_ENCODE = 8'h13;
    localparam logic [7:0] OP_NTT    = 8'h20;
    localparam logic [7:0] OP_INTT   = 8'h21;
    localparam logic [7:0] OP_BMUL   = 8'h22;
    localparam logic [7:0] OP_ADD    = 8'h23;
    localparam logic [7:0] OP_SUB    = 8'h24;

    localparam logic [31:0] ERR_PARAM   = 32'd1;
    localparam logic [31:0] ERR_EK      = 32'd2;
    localparam logic [31:0] ERR_ILLEGAL = 32'd3;

    typedef enum logic [3:0] {
        C_IDLE,
        C_FETCH,     // ROM address = pc.
        C_DECODE,    // ROM data valid: dispatch.
        C_HINIT,     // Wait for sponge idle, init.
        C_HABI,      // Absorb immediate byte(s).
        C_HFIN,      // Finalize.
        C_HSQZ,      // Squeeze to buffer.
        C_RD,        // Issue buffer read at rd_ptr.
        C_RD_WAIT,   // Buffer data valid.
        C_ABS,       // Absorb byte_x.
        C_CMP_B,     // CMP: second operand valid.
        C_UNIT,      // Wait for poly unit.
        C_NEXT       // Advance pc.
    } state_t;

    localparam int PC_W = 9;            // Program counter (mlkem_ucode_rom ADDR_W).

    state_t      state;
    logic [PC_W-1:0] pc;
    logic [7:0]  i_op;
    logic [7:0]  i_p;
    logic [13:0] ptr_a, ptr_b, ptr_c;   // Effective byte addresses.
    logic [15:0] len;
    logic [7:0]  byte_x;
    logic        imm_idx;
    logic        flag;                  // CMP mismatch (sticky per run).
    logic        ek_bad;                // Modulus-check failure (sticky per run).
    logic [13:0] in_base, out_base;
    logic [1:0]  op_idx;
    logic        unit_src_sponge;       // Unpacker fed from sponge.
    logic        hold_v, rd_pend;       // DECODE byte feeder.
    logic [15:0] imm;

    // ---------------------------------------------------------------------
    // Microcode ROM.
    // ---------------------------------------------------------------------
    logic [95:0]     rom_data;
    logic [PC_W-1:0] rom_entry;

    mlkem_ucode_rom #(
        .ADDR_W (PC_W)
    ) u_rom (
        .clk   (clk),
        .addr  (pc),
        .data  (rom_data),
        .op    (op_idx),
        .entry (rom_entry)
    );

    logic [7:0]  f_op, f_p;
    logic [15:0] f_a, f_b, f_c, f_len;
    assign f_op  = rom_data[95:88];
    assign f_p   = rom_data[87:80];
    assign f_a   = rom_data[79:64];
    assign f_b   = rom_data[63:48];
    assign f_c   = rom_data[47:32];
    assign f_len = rom_data[31:16];

    function automatic logic [13:0] eff(input logic [15:0] t,
                                        input logic [13:0] ib,
                                        input logic [13:0] ob);
        case (t[15:14])
            2'd1:    return ib + t[13:0];
            2'd2:    return ob + t[13:0];
            default: return t[13:0];
        endcase
    endfunction

    // ---------------------------------------------------------------------
    // Parameter decode.
    // ---------------------------------------------------------------------
    logic lvl_ok, op_ok;
    assign lvl_ok = (sec_level == 32'd768);
    assign op_ok  = (op_mode < 32'd3);

    // ---------------------------------------------------------------------
    // Buffer port B.
    // ---------------------------------------------------------------------
    // Byte selected from the word read in the previous cycle.
    logic [13:0] rd_ptr;
    logic [7:0]  rd_byte;
    assign rd_byte = buf_dout[{rd_ptr[1:0], 3'b000} +: 8];

    always_comb begin
        // Which pointer the current read uses.
        case (i_op)
            OP_CMP:  rd_ptr = (state == C_CMP_B) ? ptr_b : ptr_a;
            OP_CSEL: rd_ptr = flag ? ptr_b : ptr_a;
            default: rd_ptr = ptr_a;
        endcase
    end

    logic        wr_req;
    logic [13:0] wr_ptr;
    logic [7:0]  wr_byte;

    always_comb begin
        wr_req  = 1'b0;
        wr_ptr  = ptr_b;
        wr_byte = rd_byte;
        case (state)
            C_HSQZ: begin
                wr_req  = h_squeeze_valid;
                wr_ptr  = ptr_a;
                wr_byte = h_squeeze_byte;
            end
            C_RD_WAIT: begin
                if (i_op == OP_COPY) begin
                    wr_req = 1'b1;
                    wr_ptr = ptr_b;
                end else if (i_op == OP_CSEL) begin
                    wr_req = 1'b1;
                    wr_ptr = ptr_c;
                end
            end
            C_UNIT: begin
                if (i_op == OP_ENCODE) begin
                    wr_req  = pk_out_valid;
                    wr_ptr  = ptr_b;
                    wr_byte = pk_out_byte;
                end
            end
            default: ;
        endcase
    end

    logic rd_req;
    assign rd_req = (state == C_RD) || (state == C_RD_WAIT && i_op == OP_CMP) ||
                    (state == C_UNIT && i_op == OP_DECODE && !hold_v && !rd_pend);

    always_comb begin
        buf_en   = rd_req || wr_req;
        buf_we   = wr_req ? (4'b0001 << wr_ptr[1:0]) : 4'b0000;
        buf_din  = {4{wr_byte}};
        if (wr_req)
            buf_addr = wr_ptr[13:2];
        else if (state == C_RD_WAIT && i_op == OP_CMP)
            buf_addr = ptr_b[13:2];
        else
            buf_addr = rd_ptr[13:2];
    end

    // ---------------------------------------------------------------------
    // Sponge, unit handshakes.
    // ---------------------------------------------------------------------
    assign h_init         = (state == C_HINIT) && h_idle;
    assign h_mode         = i_p[1:0];
    assign h_absorb_valid = (state == C_ABS) || (state == C_HABI);
    assign h_absorb_byte  = (state == C_HABI) ? (imm_idx ? imm[15:8] : imm[7:0]) : byte_x;
    assign h_finalize     = (state == C_HFIN) && h_absorb_ready;
    assign h_squeeze_take = (state == C_HSQZ && h_squeeze_valid) ||
                            (state == C_UNIT && unit_src_sponge && up_src_take);

    assign up_src_valid = unit_src_sponge ? h_squeeze_valid : hold_v;
    assign up_src_byte  = unit_src_sponge ? h_squeeze_byte  : byte_x;

    // ---------------------------------------------------------------------
    // Sequencer.
    // ---------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state           <= C_IDLE;
            pc              <= '0;
            i_op            <= '0;
            i_p             <= '0;
            imm             <= '0;
            ptr_a           <= '0;
            ptr_b           <= '0;
            ptr_c           <= '0;
            len             <= '0;
            byte_x          <= '0;
            imm_idx         <= 1'b0;
            flag            <= 1'b0;
            ek_bad          <= 1'b0;
            in_base         <= '0;
            out_base        <= '0;
            op_idx          <= '0;
            unit_src_sponge <= 1'b0;
            hold_v          <= 1'b0;
            rd_pend         <= 1'b0;
            status_busy     <= 1'b0;
            status_done     <= 1'b0;
            status_error    <= 1'b0;
            error_code      <= '0;
            cycle_count     <= '0;
            alu_start       <= 1'b0;
            alu_op          <= '0;
            alu_sa          <= '0;
            alu_sb          <= '0;
            alu_sc          <= '0;
            alu_acc         <= 1'b0;
            up_start        <= 1'b0;
            up_mode         <= '0;
            up_param        <= '0;
            up_check        <= 1'b0;
            up_slot         <= '0;
            pk_start        <= 1'b0;
            pk_d            <= '0;
            pk_slot         <= '0;
            pr_sel          <= '0;
            units_clr       <= 1'b0;
        end else begin
            alu_start <= 1'b0;
            up_start  <= 1'b0;
            pk_start  <= 1'b0;
            units_clr <= 1'b0;

            if (status_busy)
                cycle_count <= cycle_count + 32'd1;

            if (up_range_err)
                ek_bad <= 1'b1;

            if (ctrl_reset) begin
                state        <= C_IDLE;
                status_busy  <= 1'b0;
                status_done  <= 1'b0;
                status_error <= 1'b0;
                error_code   <= '0;
                cycle_count  <= '0;
                hold_v       <= 1'b0;
                rd_pend      <= 1'b0;
                units_clr    <= 1'b1;
            end else begin
                case (state)
                    C_IDLE: begin
                        if (ctrl_start) begin
                            status_done  <= 1'b0;
                            status_error <= 1'b0;
                            error_code   <= '0;
                            cycle_count  <= '0;
                            if (!lvl_ok || !op_ok) begin
                                status_error <= 1'b1;
                                error_code   <= ERR_PARAM;
                            end else begin
                                op_idx      <= op_mode[1:0];
                                in_base     <= data_in_addr[13:0];
                                out_base    <= data_out_addr[13:0];
                                flag        <= 1'b0;
                                ek_bad      <= 1'b0;
                                status_busy <= 1'b1;
                                state       <= C_NEXT;  // Loads pc from entry.
                                pc          <= '1;
                            end
                        end
                    end

                    C_NEXT: begin
                        pc    <= (pc == '1) ? rom_entry : pc + 1'b1;
                        state <= C_FETCH;
                    end

                    C_FETCH: state <= C_DECODE;

                    C_DECODE: begin
                        i_op    <= f_op;
                        i_p     <= f_p;
                        imm     <= f_a;
                        len     <= f_len;
                        imm_idx <= 1'b0;
                        ptr_a   <= eff(f_a, in_base, out_base);
                        ptr_b   <= eff(f_b, in_base, out_base);
                        ptr_c   <= eff(f_c, in_base, out_base);
                        case (f_op)
                            OP_END: begin
                                status_busy <= 1'b0;
                                status_done <= 1'b1;
                                if (ek_bad) begin
                                    status_error <= 1'b1;
                                    error_code   <= ERR_EK;
                                end
                                state <= C_IDLE;
                            end
                            OP_HINIT: state <= C_HINIT;
                            OP_HABI:  state <= C_HABI;
                            OP_HFIN:  state <= C_HFIN;
                            OP_HSQZ:  state <= (f_len == 0) ? C_NEXT : C_HSQZ;
                            OP_HABS, OP_COPY, OP_CMP, OP_CSEL:
                                      state <= (f_len == 0) ? C_NEXT : C_RD;
                            OP_SAMPLE, OP_CBD, OP_DECODE: begin
                                up_start        <= 1'b1;
                                up_mode         <= (f_op == OP_SAMPLE) ? 2'd0 :
                                                   (f_op == OP_CBD)    ? 2'd1 : 2'd2;
                                up_param        <= f_p[3:0];
                                up_check        <= f_p[4];
                                up_slot         <= f_c[2:0];
                                unit_src_sponge <= (f_op != OP_DECODE);
                                hold_v          <= 1'b0;
                                rd_pend         <= 1'b0;
                                pr_sel          <= 2'd1;
                                state           <= C_UNIT;
                            end
                            OP_ENCODE: begin
                                pk_start        <= 1'b1;
                                pk_d            <= f_p[3:0];
                                pk_slot         <= f_a[2:0];
                                unit_src_sponge <= 1'b0;
                                pr_sel          <= 2'd2;
                                state           <= C_UNIT;
                            end
                            OP_NTT, OP_INTT, OP_BMUL, OP_ADD, OP_SUB: begin
                                alu_start       <= 1'b1;
                                alu_op          <= (f_op == OP_NTT)  ? 3'd0 :
                                                   (f_op == OP_INTT) ? 3'd1 :
                                                   (f_op == OP_BMUL) ? 3'd2 :
                                                   (f_op == OP_ADD)  ? 3'd3 : 3'd4;
                                alu_sa          <= f_a[2:0];
                                alu_sb          <= f_b[2:0];
                                alu_sc          <= f_c[2:0];
                                alu_acc         <= f_p[0];
                                unit_src_sponge <= 1'b0;
                                pr_sel          <= 2'd0;
                                state           <= C_UNIT;
                            end
                            default: begin
                                status_busy  <= 1'b0;
                                status_error <= 1'b1;
                                error_code   <= ERR_ILLEGAL;
                                state        <= C_IDLE;
                            end
                        endcase
                    end

                    C_HINIT: if (h_idle) state <= C_NEXT;

                    C_HABI: if (h_absorb_ready) begin
                        imm_idx <= 1'b1;
                        if (imm_idx || i_p == 8'd1)
                            state <= C_NEXT;
                    end

                    C_HFIN: if (h_absorb_ready) state <= C_NEXT;

                    C_HSQZ: if (h_squeeze_valid) begin
                        ptr_a <= ptr_a + 14'd1;
                        len   <= len - 16'd1;
                        if (len == 16'd1)
                            state <= C_NEXT;
                    end

                    C_RD: state <= C_RD_WAIT;

                    C_RD_WAIT: begin
                        byte_x <= rd_byte;
                        case (i_op)
                            OP_HABS: state <= C_ABS;
                            OP_CMP:  state <= C_CMP_B;  // ptr_b read issued.
                            default: begin              // COPY / CSEL: byte written.
                                ptr_a <= ptr_a + 14'd1;
                                ptr_b <= ptr_b + 14'd1;
                                ptr_c <= ptr_c + 14'd1;
                                len   <= len - 16'd1;
                                state <= (len == 16'd1) ? C_NEXT : C_RD;
                            end
                        endcase
                    end

                    C_CMP_B: begin
                        if (rd_byte != byte_x)
                            flag <= 1'b1;
                        ptr_a <= ptr_a + 14'd1;
                        ptr_b <= ptr_b + 14'd1;
                        len   <= len - 16'd1;
                        state <= (len == 16'd1) ? C_NEXT : C_RD;
                    end

                    C_ABS: if (h_absorb_ready) begin
                        ptr_a <= ptr_a + 14'd1;
                        len   <= len - 16'd1;
                        state <= (len == 16'd1) ? C_NEXT : C_RD;
                    end

                    C_UNIT: begin
                        // DECODE byte feeder: one-byte holding register.
                        if (i_op == OP_DECODE) begin
                            if (rd_req) begin
                                rd_pend <= 1'b1;
                            end else if (rd_pend) begin
                                rd_pend <= 1'b0;
                                hold_v  <= 1'b1;
                                byte_x  <= rd_byte;
                                ptr_a   <= ptr_a + 14'd1;
                            end else if (hold_v && up_src_take) begin
                                hold_v  <= 1'b0;
                            end
                        end
                        if (i_op == OP_ENCODE && pk_out_valid)
                            ptr_b <= ptr_b + 14'd1;
                        if (alu_done || up_done || pk_done)
                            state <= C_NEXT;
                    end

                    default: state <= C_IDLE;
                endcase
            end
        end
    end

endmodule
