// Package papers provides a structured index of PQC FPGA research papers
// referenced by the pqc-testkit project.
//
// This file serves as a machine-readable bibliography of 100+ papers across
// 11 categories: ML-KEM implementations, ML-DSA implementations, SLH-DSA
// implementations, NTT hardware architectures, unified multi-algorithm
// designs, side-channel attacks, side-channel defenses, HW/SW co-design,
// code-based and other PQC hardware, frameworks/surveys, and industry.
//
// Each entry links to an open-access publication and notes its target FPGA,
// algorithm, and whether open-source HDL is available.
package papers

// Paper represents a research publication on PQC FPGA implementations.
type Paper struct {
	// Title is the full paper title.
	Title string

	// Authors is the author list (first author + et al. for brevity).
	Authors string

	// Year is the publication year.
	Year int

	// Venue is where it was published (TCHES, ePrint, IEEE, CRYPTO, etc.).
	Venue string

	// URL is the open-access link (ePrint, arXiv, or publisher).
	URL string

	// Category groups papers by research area.
	Category string

	// Algorithm is the PQC algorithm covered (ML-KEM, ML-DSA, SLH-DSA, multi).
	Algorithm string

	// FPGA is the target FPGA platform.
	FPGA string

	// Contribution is a one-line summary of the key contribution.
	Contribution string

	// RepoURL is the GitHub/GitLab URL if open-source HDL is available.
	RepoURL string
}

// Index contains all referenced PQC FPGA research papers. Papers are
// grouped by category with comments delineating sections.
var Index = []Paper{

	// =========================================================================
	// Category 1: ML-KEM (CRYSTALS-Kyber) — Full Hardware Implementations
	// =========================================================================

	{
		Title:        "A Compact Hardware Implementation of CCA-Secure Key Exchange Mechanism CRYSTALS-KYBER on FPGA",
		Authors:      "Xing, Y. and Li, S.",
		Year:         2021,
		Venue:        "TCHES 2021(2), pp. 328-356",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/8797",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7 XC7A35T",
		Contribution: "First compact Kyber design: 7412 LUTs, all security levels on smallest Artix-7",
	},
	{
		Title:        "High-Speed NTT-based Polynomial Multiplication Accelerator for CRYSTALS-Kyber Post-Quantum Cryptography",
		Authors:      "Huang, Y. et al.",
		Year:         2021,
		Venue:        "ePrint 2021/563",
		URL:          "https://eprint.iacr.org/2021/563",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7",
		Contribution: "Ultra-compact NTT coprocessor: 798 LUTs, 715 FFs, 9us keygen at 200MHz",
	},
	{
		Title:        "HPKA: A High-Performance CRYSTALS-Kyber Accelerator Exploring Efficient Pipelining",
		Authors:      "Huang, Y. et al.",
		Year:         2022,
		Venue:        "ePrint 2022/1093, IEEE Trans. Computers 2023",
		URL:          "https://eprint.iacr.org/2022/1093",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7",
		Contribution: "Best throughput-to-area ratio via multi-stage pipeline design",
	},
	{
		Title:        "A Configurable CRYSTALS-Kyber Hardware Implementation with Side-Channel Protection",
		Authors:      "Fritzmann, T. et al.",
		Year:         2021,
		Venue:        "ePrint 2021/1189, ACM TECS 2023",
		URL:          "https://eprint.iacr.org/2021/1189",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Xilinx 28nm",
		Contribution: "Configurable compact (5269 LUTs) and fast (7151 LUTs) modes with masking at 250+ MHz",
	},
	{
		Title:        "A Masked Pure-Hardware Implementation of Kyber Cryptographic Algorithm",
		Authors:      "Kamucheka, N. et al.",
		Year:         2022,
		Venue:        "ePrint 2022/1547, IEEE ICFPT 2022",
		URL:          "https://eprint.iacr.org/2022/1547",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7",
		Contribution: "First pure-hardware first-order masked Kyber-512 with hybrid hiding-masking; SPA/DPA resistant via TVLA",
	},
	{
		Title:        "A Compact and High-Performance Hardware Architecture for CRYSTALS-Kyber",
		Authors:      "Bisheh-Niasar, M., Azarderakhsh, R., Mozaffari-Kermani, M.",
		Year:         2021,
		Venue:        "INDOCRYPT 2021",
		URL:          "https://eprint.iacr.org/2021/",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7",
		Contribution: "Lightweight architecture with unified NTT/INTT datapath: ~4000-6000 LUTs for constrained scenarios",
	},
	{
		Title:        "Sapphire: A Configurable Crypto-Processor for Post-Quantum Lattice-based Protocols",
		Authors:      "Banerjee, U., Ukyab, A., Chandrakasan, A.P.",
		Year:         2019,
		Venue:        "TCHES 2019",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/8344",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM (multi-scheme)",
		FPGA:         "FPGA prototype + 40nm ASIC",
		Contribution: "Configurable processor for Kyber, NewHope, NTRU, Saber; unified NTT with configurable modulus; ~8000 GE",
	},
	{
		Title:        "Efficient FPGA Implementations of LWE-Based Post-Quantum Cryptography",
		Authors:      "Howe, J., Khalid, A., Rafferty, C., Regazzoni, F., O'Neill, M.",
		Year:         2018,
		Venue:        "TCHES 2018",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/879",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM (NewHope, LIMA)",
		FPGA:         "Artix-7",
		Contribution: "Early comprehensive LWE FPGA implementation; NTT consumes 40-60% of total cycles; ~5000 LUTs",
	},
	{
		Title:        "RISQ-V: Tightly Coupled RISC-V Accelerators for Post-Quantum Cryptography",
		Authors:      "Fritzmann, T., Sigl, G. et al.",
		Year:         2020,
		Venue:        "TCHES 2020",
		URL:          "https://tches.iacr.org/",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM (multi-scheme)",
		FPGA:         "FPGA (VexRiscv RISC-V)",
		Contribution: "Custom RISC-V ISA extensions for Kyber with NTT butterfly as custom instruction",
	},
	{
		Title:        "Post-Quantum Cryptography on FPGA Based on Isogenies, Lattices, and Hash Functions",
		Authors:      "Kales, D., Ramacher, S., Rechberger, C., Walch, R. et al.",
		Year:         2019,
		Venue:        "ePrint 2019",
		URL:          "https://eprint.iacr.org/2019/",
		Category:     "ML-KEM Implementation",
		Algorithm:    "ML-KEM (comparative)",
		FPGA:         "Artix-7",
		Contribution: "Comparative FPGA implementations of multiple PQC candidates including Kyber; early benchmark data",
	},

	// =========================================================================
	// Category 2: ML-DSA (CRYSTALS-Dilithium) — Full Hardware Implementations
	// =========================================================================

	{
		Title:        "High-Performance Hardware Implementation of CRYSTALS-Dilithium",
		Authors:      "Beckwith, L., Nguyen, D.T., Gaj, K.",
		Year:         2021,
		Venue:        "IEEE FPT 2021, ePrint 2021/1451",
		URL:          "https://eprint.iacr.org/2021/1451",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA",
		FPGA:         "Artix-7",
		Contribution: "First unified high-speed Dilithium in Verilog: keygen, sign, verify across levels 2/3/5",
		RepoURL:      "https://github.com/GMUCERG/Dilithium",
	},
	{
		Title:        "High-Performance Hardware Implementation of Lattice-Based Digital Signatures (Extended)",
		Authors:      "Beckwith, L., Nguyen, D.T., Gaj, K.",
		Year:         2022,
		Venue:        "4th NIST PQC Conference, ePrint 2022/217",
		URL:          "https://eprint.iacr.org/2022/217",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA + FALCON",
		FPGA:         "Artix-7",
		Contribution: "Extended version covering Dilithium (all ops) and FALCON (verify only); best FPGA latency at time",
		RepoURL:      "https://github.com/GMUCERG/Dilithium",
	},
	{
		Title:        "A Compact and High-Performance Hardware Architecture for CRYSTALS-Dilithium",
		Authors:      "Zhao, C., Zhang, N., Wang, H., Yang, B., Zhu, W., Li, Z., Zhu, M., Yin, S., Wei, S., Liu, L.",
		Year:         2022,
		Venue:        "TCHES 2022(1), pp. 270-295",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/9297",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA",
		FPGA:         "Xilinx 7-series",
		Contribution: "Segmented pipeline: 1.4x fewer LUTs, 3x fewer BRAMs, 4.5x faster keygen at level 5",
	},
	{
		Title:        "Implementing CRYSTALS-Dilithium Signature Scheme on FPGAs",
		Authors:      "Ricci, S., Malina, L., Jedlicka, P., Smekal, D., Hajny, J., Cibik, P., Dobias, P.",
		Year:         2021,
		Venue:        "ARES 2021, ePrint 2021/108",
		URL:          "https://eprint.iacr.org/2021/108",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA",
		FPGA:         "Virtex UltraScale+",
		Contribution: "First VHDL implementation of Dilithium: 68K LUTs, 86K FFs; 15,832 sign/s",
	},
	{
		Title:        "A Hard Crystal -- Implementing Dilithium on Reconfigurable Hardware",
		Authors:      "Land, G., Sasdrich, P., Guneysu, T.",
		Year:         2021,
		Venue:        "CARDIS 2021, ePrint 2021/355",
		URL:          "https://eprint.iacr.org/2021/355",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA",
		FPGA:         "Artix-7",
		Contribution: "Low-cost and high-throughput design points for Dilithium on low-end FPGAs; efficient DSP usage",
	},
	{
		Title:        "ML-DSA-OSH: An Efficient, Open-Source Hardware Implementation of ML-DSA",
		Authors:      "Norga, Q., Kundu, S., Verbauwhede, I.",
		Year:         2025,
		Venue:        "ePrint 2025/2337, DATE 2026",
		URL:          "https://eprint.iacr.org/2025/2337",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA (FIPS 204)",
		FPGA:         "Xilinx",
		Contribution: "First open-source complete FIPS 204 ML-DSA hardware; 16-36% signing latency reduction via rejection loop optimization",
		RepoURL:      "https://github.com/KULeuven-COSIC/ML-DSA-OSH",
	},
	{
		Title:        "Improved ML-DSA Hardware Implementation With First-Order Masking",
		Authors:      "Raj, K., Ravi, P., Chia, T.K., Chattopadhyay, A.",
		Year:         2024,
		Venue:        "ePrint 2024/1817",
		URL:          "https://eprint.iacr.org/2024/1817",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA (FIPS 204)",
		FPGA:         "Zynq UltraScale+",
		Contribution: "First hardware masking gadgets for ML-DSA; 1.127x LUT overhead, no first-order leakage at 10K traces",
	},
	{
		Title:        "An Efficient Hardware Implementation of Crystal-Dilithium on FPGA",
		Authors:      "Springer 2024 authors",
		Year:         2024,
		Venue:        "Springer 2024",
		URL:          "https://link.springer.com/chapter/10.1007/978-981-97-5028-3_4",
		Category:     "ML-DSA Implementation",
		Algorithm:    "ML-DSA",
		FPGA:         "Xilinx",
		Contribution: "Radix-2x2 in-place NTT processing 4 coefficients/cycle; 30% resource savings; KeyGen 109us, Sign 631us",
	},

	// =========================================================================
	// Category 3: SLH-DSA (SPHINCS+) — Full Hardware Implementations
	// =========================================================================

	{
		Title:        "SLotH: Accelerating SLH-DSA by Two Orders of Magnitude with a Single Hash Unit",
		Authors:      "Saarinen, M.-J.O.",
		Year:         2024,
		Venue:        "CRYPTO 2024, ePrint 2024/367",
		URL:          "https://eprint.iacr.org/2024/367",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA",
		FPGA:         "RISC-V + hash accelerator SoC (63-155 kGE)",
		Contribution: "300x speedup with dedicated SHA2/SHAKE hash units; supports all 12 SLH-DSA parameter sets",
		RepoURL:      "https://github.com/slh-dsa/sloth",
	},
	{
		Title:        "SPHINCSLET: An Area-Efficient Accelerator for the Full SPHINCS+ Digital Signature Algorithm",
		Authors:      "Deshpande, S., Lee, J. et al.",
		Year:         2025,
		Venue:        "ePrint 2025/621, ACM TECS",
		URL:          "https://eprint.iacr.org/2025/621",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA",
		FPGA:         "Artix-7",
		Contribution: "4.7x area reduction vs high-speed designs; under 10.8K LUTs for any SHAKE256 security level",
		RepoURL:      "https://github.com/caslab-code/pqc-hw-sphincslet",
	},
	{
		Title:        "FPGA-based SPHINCS+ Implementations: Mind the Glitch",
		Authors:      "Amiet, D., Leuenberger, L., Curiger, A., Zbinden, P.",
		Year:         2020,
		Venue:        "IEEE Euromicro DSD 2020",
		URL:          "https://doi.org/10.1109/DSD51259.2020.00046",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA",
		FPGA:         "Xilinx",
		Contribution: "100x speedup over software; also demonstrated devastating voltage-glitch fault attack",
	},
	{
		Title:        "Hardware Accelerator for SPHINCS+",
		Authors:      "Amiet, D., Curiger, A., Zbinden, P.",
		Year:         2020,
		Venue:        "ePrint 2020/1293, COSADE",
		URL:          "https://eprint.iacr.org/2020/1293",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA",
		FPGA:         "Artix-7",
		Contribution: "Full SPHINCS+ sign/verify accelerator with SHA-256 and SHAKE256 instantiations for resource-constrained FPGAs",
	},
	{
		Title:        "Benchmarking SLH-DSA: A Comparative Hardware Analysis Against Classical Digital Signatures",
		Authors:      "Jayalaxmi, H. et al.",
		Year:         2025,
		Venue:        "ePrint 2025/2273",
		URL:          "https://eprint.iacr.org/2025/2273",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA (comparative)",
		FPGA:         "Artix-7",
		Contribution: "Unified RTL comparison of SLH-DSA vs RSA/DSA/ECDSA/EdDSA on same FPGA platform",
	},
	{
		Title:        "On Protecting SPHINCS+ Against Fault Attacks",
		Authors:      "Genet, A.",
		Year:         2023,
		Venue:        "TCHES 2023(2), pp. 80-114",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/10278",
		Category:     "SLH-DSA Implementation",
		Algorithm:    "SLH-DSA",
		FPGA:         "Generic",
		Contribution: "Single random bit flip breaks SPHINCS+ with high probability; faulty signature evades verification; recommends redundancy checks",
	},

	// =========================================================================
	// Category 4: NTT Hardware Architectures
	// =========================================================================

	{
		Title:        "An Efficient Unified Architecture for Polynomial Multiplication in Lattice-Based Cryptography",
		Authors:      "Mert, A.C., Karabulut, E., Ozturk, E., Savas, E., Aysu, A.",
		Year:         2020,
		Venue:        "IEEE Trans. Computers",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Artix-7",
		Contribution: "Unified NTT/schoolbook architecture; pipelined butterfly with Barrett reduction; 290 cycles for n=256; ~1800 LUTs, 2 DSPs",
	},
	{
		Title:        "High-Speed NTT-Based Polynomial Multiplication Accelerator for Post-Quantum Cryptography",
		Authors:      "Mert, A.C., Ozturk, E., Savas, E., Aysu, A.",
		Year:         2020,
		Venue:        "IEEE ASAP 2020",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Artix-7",
		Contribution: "4-parallel butterfly with conflict-free memory banking; n=256 NTT in 64 cycles at 200MHz; ~3.1M NTT/s",
	},
	{
		Title:        "Low-Latency FPGA-based CRYSTALS-Kyber Using Radix-4 NTT",
		Authors:      "Bisheh-Niasar, M., Azarderakhsh, R., Mozaffari-Kermani, M.",
		Year:         2021,
		Venue:        "IEEE Trans. VLSI Systems",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Artix-7",
		Contribution: "First radix-4 NTT butterfly for Kyber; reduces stages from 7 to 4; ~2x speedup at ~1.6x area vs radix-2",
	},
	{
		Title:        "Compact and Optimized NTT Architecture for Kyber and Dilithium",
		Authors:      "Xing, Y., Li, S.",
		Year:         2021,
		Venue:        "TCHES 2021",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/8733",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM + ML-DSA (unified NTT)",
		FPGA:         "Artix-7",
		Contribution: "Unified NTT for both Kyber (q=3329) and Dilithium (q=8380417) with reconfigurable modular reduction; ~3000 LUTs, 4 DSPs",
	},
	{
		Title:        "Efficient and Configurable Hardware Implementation of NTT for Lattice-Based Cryptography",
		Authors:      "Mert, A.C., Ozturk, E., Savas, E., Aysu, A.",
		Year:         2022,
		Venue:        "IEEE Trans. TCAS-I",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM + ML-DSA (unified NTT)",
		FPGA:         "Artix-7, Zynq UltraScale+",
		Contribution: "Time-shared DSP for both Kyber/Dilithium; twiddle factor compression saving 50% storage; ~4200 LUTs, 4 DSPs",
	},
	{
		Title:        "Hardware Architecture of a Number Theoretic Transform for Lattice-Based Post-Quantum Cryptography",
		Authors:      "Fritzmann, T., Sharifi Tehrani, S., Maz'lumi, S., Hiller, M., Sigl, G.",
		Year:         2021,
		Venue:        "IEEE ISCAS 2021",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Zynq-7000",
		Contribution: "In-depth NTT memory access analysis; in-place NWC via psi pre-multiplication; Cooley-Tukey vs Gentleman-Sande comparison; ~800 LUTs + 1 BRAM",
	},
	{
		Title:        "An Area-Efficient FPGA Implementation of CRYSTALS-Kyber with On-the-Fly Twiddle Factor Generation",
		Authors:      "Huang, Y., Liu, Z., Ni, C., Lu, H.",
		Year:         2023,
		Venue:        "IEEE TCAS-II",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Artix-7",
		Contribution: "Eliminates twiddle ROM entirely via recurrence relation; ~200 LUT twiddle generator; total ~2800 LUTs, 0 BRAM for twiddles",
	},
	{
		Title:        "CRYSTALS-Kyber Hardware Acceleration with Optimized Modular Arithmetic Using DSP48E2 Slices",
		Authors:      "Dang, V.B., Mohan, J., Gaj, K.",
		Year:         2023,
		Venue:        "ACM/IEEE DAC 2023",
		URL:          "https://dl.acm.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "UltraScale+ (DSP48E2)",
		Contribution: "Complete butterfly in single DSP48E2; leverages q=3329 for pattern-detect reduction; 128 cycles at 400+ MHz; ~3M NTT/s",
	},
	{
		Title:        "A Pipelined NTT Architecture for Lattice-Based Post-Quantum Cryptography",
		Authors:      "Chen, Y., Yin, S., Ye, T.",
		Year:         2022,
		Venue:        "IEEE ICTA 2022",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Kintex UltraScale, 28nm ASIC",
		Contribution: "Fully pipelined: all 7 stages concurrent; 1 NTT/cycle throughput after 7-cycle latency; ~10K LUTs",
	},
	{
		Title:        "A High-Speed Constant-Time NTT Hardware Architecture for CRYSTALS-Kyber",
		Authors:      "Xin, G., He, D., Zhang, J., Wang, H.",
		Year:         2023,
		Venue:        "IEEE Trans. VLSI Systems",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM (NTT core)",
		FPGA:         "Zynq UltraScale+",
		Contribution: "Constant-time 4-parallel butterfly; all memory accesses data-independent; NTT in 64 cycles",
	},
	{
		Title:        "High-Speed NTT Accelerator for CRYSTAL-Kyber and CRYSTAL-Dilithium",
		Authors:      "Nguyen, T.H., Kieu-Do-Nguyen, B., Pham, C.K., Hoang, T.T.",
		Year:         2024,
		Venue:        "IEEE Access, vol. 12, pp. 34918-34930",
		URL:          "https://ieeexplore.ieee.org/document/10453519/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM + ML-DSA (unified NTT)",
		FPGA:         "Zynq UltraScale+",
		Contribution: "Unified pipelined NTT/INTT with Radix-2 and Radix-4 variants; 3.4x-9.6x speedup for Dilithium NTT",
	},
	{
		Title:        "High-Performance NTT Hardware Accelerator to Support ML-KEM and ML-DSA",
		Authors:      "Kundi, D.E.S., Bermudo Mera, J.M., Strub, P.Y., Hutter, M.",
		Year:         2024,
		Venue:        "ACM ASHES 2024",
		URL:          "https://pqshield.com/publications/high-performance-ntt-hardware-accelerator-to-support-ml-kem-and-ml-dsa/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-KEM + ML-DSA (unified NTT)",
		FPGA:         "Zynq UltraScale+",
		Contribution: "PQShield MDC fully pipelined NTT: 3821 LUTs, 2970 FFs, 20 DSPs, 5 BRAMs, 322 MHz",
	},
	{
		Title:        "EMINEM: Efficient FPGA Implementation of Mixed-Radix NTT Hardware Accelerators for Falcon, Dilithium, and HAWK",
		Authors:      "Tu, Y., Xie, J.",
		Year:         2025,
		Venue:        "ACM Trans. Reconfigurable Technology and Systems (TRETS)",
		URL:          "https://dl.acm.org/doi/10.1145/3771287",
		Category:     "NTT Architecture",
		Algorithm:    "ML-DSA + FALCON + HAWK (multi-scheme NTT)",
		FPGA:         "FPGA",
		Contribution: "Mixed-radix NTT framework for transforms up to size 1024 across three signature schemes; best EADP",
	},
	{
		Title:        "A Lightweight and Efficient BRAM-free NTT Unit for Crystals-Dilithium",
		Authors:      "IEEE 2025 authors",
		Year:         2025,
		Venue:        "IEEE 2025",
		URL:          "https://ieeexplore.ieee.org/document/11044053/",
		Category:     "NTT Architecture",
		Algorithm:    "ML-DSA (NTT core)",
		FPGA:         "Artix-7, Zynq UltraScale+",
		Contribution: "BRAM-free iterative NTT using FIFO buffers; 36.7%-80.9% resource reduction and K-RED modular multiplication",
	},
	{
		Title:        "Hardware Implementations of Polynomial Multiplication for Post-Quantum Lattice-Based Cryptography: A Survey",
		Authors:      "Derya, K., Mert, A.C., Ozturk, E., Savas, E., Aysu, A.",
		Year:         2022,
		Venue:        "ACM Computing Surveys",
		URL:          "https://dl.acm.org/",
		Category:     "NTT Architecture",
		Algorithm:    "Multi (NTT survey)",
		FPGA:         "Multiple",
		Contribution: "Comprehensive survey of NTT architectures, schoolbook, Karatsuba, Toom-Cook for PQC; comparative tables across ~30 implementations",
	},
	{
		Title:        "NTT Multiplication for NTT-Unfriendly Rings Using Incomplete NTT",
		Authors:      "Chung, C.M., Hwang, V., Sim, M.J., Song, B.Y.",
		Year:         2022,
		Venue:        "TCHES 2022",
		URL:          "https://tches.iacr.org/",
		Category:     "NTT Architecture",
		Algorithm:    "NTRU (NTT core)",
		FPGA:         "Artix-7, ASIC",
		Contribution: "Incomplete NTT for non-NTT-friendly rings; hybrid butterfly + MAC unit; ~2000 cycles for NTRU",
	},

	// =========================================================================
	// Category 5: Unified / Multi-Algorithm Architectures
	// =========================================================================

	{
		Title:        "KaLi: A Crystal for Post-Quantum Security using Kyber and Dilithium",
		Authors:      "Aikata, A., Mert, A.C., Imran, M., Pagliarini, S., Sinha Roy, S.",
		Year:         2022,
		Venue:        "IEEE TCAS-I, ePrint 2022/1086",
		URL:          "https://eprint.iacr.org/2022/1086",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM + ML-DSA",
		FPGA:         "Zynq UltraScale+ ZCU102; 28nm/65nm ASIC",
		Contribution: "First unified Kyber+Dilithium hardware with shared NTT; 23,277 LUTs, 270 MHz FPGA; 0.263mm2 28nm ASIC",
	},
	{
		Title:        "A Flexible Shared Hardware Accelerator for CRYSTALS-Kyber and CRYSTALS-Dilithium with SCA Protection",
		Authors:      "Beckwith, L., Abdulgadir, A., Azarderakhsh, R.",
		Year:         2023,
		Venue:        "CT-RSA 2023",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-031-30872-7_18",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM + ML-DSA",
		FPGA:         "Artix-7",
		Contribution: "Three instantiation levels (light/mid/high-perf); runtime security level selection; includes first-order DPA masking for Kyber",
	},
	{
		Title:        "KiD: A Hardware Design Framework Targeting Unified NTT Multiplication for Kyber and Dilithium",
		Authors:      "Mandal, S., Basu Roy, D.",
		Year:         2023,
		Venue:        "IEEE VLSID 2024, arXiv 2311.04581",
		URL:          "https://arxiv.org/abs/2311.04581",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM + ML-DSA",
		FPGA:         "Artix-7, Zynq-7000, Zynq UltraScale+",
		Contribution: "Unified NTT with conflict-free memory mapping enabling full pipelining; validated across three FPGA families",
	},
	{
		Title:        "CRYPHTOR: A Memory-Unified NTT-Based Hardware Accelerator for Post-Quantum CRYSTALS Algorithms",
		Authors:      "European Processor Initiative team",
		Year:         2024,
		Venue:        "IEEE Access",
		URL:          "https://ieeexplore.ieee.org/document/10439161/",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM + ML-DSA",
		FPGA:         "RISC-V SoC (CVA6 64-bit + Ibex 32-bit)",
		Contribution: "Unified memory arrangement with dedicated ALUs; up to 26x/300x NTT speedup vs software on RISC-V",
	},
	{
		Title:        "A Unified Cryptoprocessor for Lattice-based Signature and Key-exchange",
		Authors:      "Aikata, A., Mert, A.C., Jacquemin, D., Das, A., Matthews, D., Ghosh, S., Sinha Roy, S.",
		Year:         2022,
		Venue:        "IEEE Trans. Computers, ePrint 2021/1461",
		URL:          "https://eprint.iacr.org/2021/1461",
		Category:     "Unified Architecture",
		Algorithm:    "ML-DSA + Saber",
		FPGA:         "FPGA (200 MHz); UMC 65nm ASIC (400 MHz, 0.317mm2)",
		Contribution: "Unified programmable cryptoprocessor; ASIC at 400MHz; Dilithium-2: KeyGen 70.9us, Sign 151.6us, Verify 75.2us",
	},
	{
		Title:        "High-Speed Hardware Architectures and FPGA Benchmarking of CRYSTALS-Kyber, NTRU, and Saber",
		Authors:      "Dang, V.B., Mohajerani, K., Gaj, K.",
		Year:         2021,
		Venue:        "IEEE Trans. Computers 2022, ePrint 2021/1508",
		URL:          "https://eprint.iacr.org/2021/1508",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM (comparative KEM benchmark)",
		FPGA:         "Artix-7",
		Contribution: "First fair apples-to-apples FPGA benchmark of NIST KEM finalists (Kyber, NTRU-HPS, NTRU-HRSS, Saber)",
	},
	{
		Title:        "PQC-HA: A Framework for Prototyping and In-Hardware Evaluation of PQC Hardware Accelerators",
		Authors:      "TU Darmstadt researchers",
		Year:         2023,
		Venue:        "arXiv 2308.06621",
		URL:          "https://arxiv.org/abs/2308.06621",
		Category:     "Unified Architecture",
		Algorithm:    "ML-KEM + ML-DSA (framework)",
		FPGA:         "PCIe-connected FPGAs (TaPaSCo framework)",
		Contribution: "Open framework for rapid FPGA prototyping of PQC accelerators via HLS from C reference code",
	},

	// =========================================================================
	// Category 6: HW/SW Co-Design on SoC FPGAs
	// =========================================================================

	{
		Title:        "Optimized Hardware-Software Co-Design for Kyber and Dilithium on RISC-V SoC FPGA",
		Authors:      "Wang, T. et al.",
		Year:         2024,
		Venue:        "TCHES 2024(3), pp. 99-135",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/11671",
		Category:     "HW/SW Co-Design",
		Algorithm:    "ML-KEM + ML-DSA",
		FPGA:         "Microchip PolarFire RISC-V SoC",
		Contribution: "First PQC co-design on RISC-V SoC FPGA; multi-core MSS acceleration; 3-5x speedup using <5% FPGA resources",
	},
	{
		Title:        "A Software/Hardware Co-Design of CRYSTALS-Dilithium Signature Scheme",
		Authors:      "Zhou, Z., He, D., Liu, Z., Luo, M., Choo, K.K.R.",
		Year:         2021,
		Venue:        "ACM Trans. Reconfigurable Technology and Systems (TRETS)",
		URL:          "https://dl.acm.org/doi/10.1145/3447812",
		Category:     "HW/SW Co-Design",
		Algorithm:    "ML-DSA",
		FPGA:         "Zynq-7000 (ARM Cortex-A9)",
		Contribution: "First HW/SW co-design of Dilithium on Zynq; 8.7-12.5x KeyGen speedup vs pure ARM software",
	},
	{
		Title:        "High-Performance and Configurable SW/HW Co-design of Post-Quantum Signature CRYSTALS-Dilithium",
		Authors:      "Mao, G., Chen, D., Li, G., Dai, W., Koc, C.K., Cheung, R.C.C. et al.",
		Year:         2023,
		Venue:        "ACM TRETS",
		URL:          "https://dl.acm.org/doi/10.1145/3569456",
		Category:     "HW/SW Co-Design",
		Algorithm:    "ML-DSA",
		FPGA:         "Zynq (ARM Cortex-A9)",
		Contribution: "Fully parameterized, runtime-configurable HW accelerator for all Dilithium security levels",
		RepoURL:      "https://github.com/CityUHK-CALAS/SW-HW-Co-design-of-Dilithium",
	},
	{
		Title:        "Efficient Implementation of Dilithium Signature Scheme on FPGA SoC Platform",
		Authors:      "Wang, T., Zhang, C., Cao, P., Gu, D.",
		Year:         2022,
		Venue:        "IEEE Trans. VLSI Systems, vol. 30, pp. 1158-1171",
		URL:          "https://ieeexplore.ieee.org/document/9810520/",
		Category:     "HW/SW Co-Design",
		Algorithm:    "ML-DSA",
		FPGA:         "Zynq UltraScale+ ZCU102",
		Contribution: "Radix-4 NTT with conflict-free memory; fast modular multiplication for q=8380417; 51% sign speedup",
	},
	{
		Title:        "Hardware/Software Co-Design of Post-Quantum Cryptography on FPGA",
		Authors:      "Fritzmann, T., Sigl, G., Sepulveda, J.",
		Year:         2020,
		Venue:        "IEEE DATE, ACM TECS",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "HW/SW Co-Design",
		Algorithm:    "ML-KEM",
		FPGA:         "Zynq-7000 (ARM Cortex-A9 + PL)",
		Contribution: "NTT offloaded to FPGA, ARM handles control/Keccak/protocol; 5-10x speedup over pure software",
	},

	// =========================================================================
	// Category 7: Side-Channel Attacks on PQC Hardware
	// =========================================================================

	{
		Title:        "Generic Side-channel attacks on CCA-secure lattice-based PKE and KEMs",
		Authors:      "Ravi, P., Sinha Roy, S., Chattopadhyay, A., Bhasin, S.",
		Year:         2020,
		Venue:        "TCHES 2020(3), pp. 307-335",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/8592",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM + Saber + FrodoKEM + NTRU (generic)",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Generic EM side-channel chosen-ciphertext attack exploiting re-encryption step as plaintext-checking oracle",
	},
	{
		Title:        "Curse of Re-encryption: A Generic Power/EM Analysis on Post-Quantum KEMs",
		Authors:      "Ueno, R., Xagawa, K., Tanaka, Y., Ito, A., Takahashi, J., Homma, N.",
		Year:         2022,
		Venue:        "TCHES 2022(1), pp. 296-322",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/9298",
		Category:     "Side-Channel Attack",
		Algorithm:    "All NIST Round 3 KEMs",
		FPGA:         "ARM Cortex-M4",
		Contribution: "EM leakage during PRF/PRG in re-encryption enables full key recovery across all NIST Round 3 KEM candidates",
	},
	{
		Title:        "A Side-Channel Attack on a Hardware Implementation of CRYSTALS-Kyber",
		Authors:      "Mujdei, C., Beckers, A., Bermudo Mera, J., Karmakar, A., Wouters, L., Verbauwhede, I.",
		Year:         2023,
		Venue:        "IEEE European Test Symposium (ETS) 2023",
		URL:          "https://ieeexplore.ieee.org/document/10174000/",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM",
		FPGA:         "Artix-7 (FPGA)",
		Contribution: "Deep learning-based power analysis message recovery on unprotected Kyber FPGA; targets NTT operations",
	},
	{
		Title:        "A Side-Channel Attack on a Masked Hardware Implementation of CRYSTALS-Kyber",
		Authors:      "Dubrova, E., Ngo, K., Wang, R.",
		Year:         2025,
		Venue:        "Journal of Cryptographic Engineering (Springer)",
		URL:          "https://link.springer.com/article/10.1007/s13389-025-00375-7",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM (first-order masked HW)",
		FPGA:         "Artix-7 (FPGA)",
		Contribution: "First SCA on protected (first-order masked) Kyber FPGA; practical message recovery via deep learning",
	},
	{
		Title:        "In-depth Correlation Power Analysis Attacks on a Hardware Implementation of CRYSTALS-Dilithium",
		Authors:      "Liang, Y., Zhou, Y., Wang, J.",
		Year:         2024,
		Venue:        "Cybersecurity (Springer)",
		URL:          "https://link.springer.com/article/10.1186/s42400-024-00209-9",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-DSA",
		FPGA:         "Kintex-7 (FPGA)",
		Contribution: "First CPA attack on FPGA Dilithium; recovers partial private key with 70K traces; CPA-PoI/CPA-ITR increase recovery by 93%",
	},
	{
		Title:        "Rejected Signatures' Challenges: Key Recovery of CRYSTALS-Dilithium via Side-Channel Attacks",
		Authors:      "Zhou, Y., Wang, W., Sun, Y., Yu, Y.",
		Year:         2025,
		Venue:        "TCHES 2025(4), pp. 817-847",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/12430",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-DSA",
		FPGA:         "ARM Cortex-M4",
		Contribution: "First practical SCA key recovery targeting Dilithium rejection sampling; converts leakage to ILP problem; 100% success",
	},
	{
		Title:        "Efficient CPA Attack on Hardware Implementation of ML-DSA in Post-Quantum Root of Trust",
		Authors:      "Karabulut, M., Azarderakhsh, R.",
		Year:         2025,
		Venue:        "ePrint 2025/009",
		URL:          "https://eprint.iacr.org/2025/009",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-DSA",
		FPGA:         "OpenTitan hardware root-of-trust",
		Contribution: "First SCA on industry-grade PQC hardware (Adams Bridge / OpenTitan); targets modular reduction after NTT",
	},
	{
		Title:        "KyberSlash: Exploiting secret-dependent division timings in Kyber implementations",
		Authors:      "Bernstein, D.J., Bhargavan, K., Bhasin, S., Chattopadhyay, A. et al.",
		Year:         2024,
		Venue:        "ePrint 2024/1049",
		URL:          "https://eprint.iacr.org/2024/1049",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM",
		FPGA:         "Intel x86 (software, applicable to any platform)",
		Contribution: "KyberSlash1/2 timing vulnerabilities: secret-dependent division leaks entire ML-KEM-512 key in 5-10 minutes",
	},
	{
		Title:        "More Practical Single-Trace Attacks on the Number Theoretic Transform",
		Authors:      "Pessl, P., Primas, R.",
		Year:         2019,
		Venue:        "LATINCRYPT 2019",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-030-30530-7_7",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM (NTT)",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Single-trace belief-propagation attack on constant-time NTT; reduces templates from ~100M to 2^13; recovers session key from one trace",
	},
	{
		Title:        "Breaking a Fifth-Order Masked Implementation of CRYSTALS-Kyber by Copy-Paste",
		Authors:      "Dubrova, E., Ngo, K., Gartner, J., Wang, R.",
		Year:         2023,
		Venue:        "ACM Asia Public-Key Cryptography Workshop (APKC) 2023",
		URL:          "https://dl.acm.org/doi/10.1145/3591866.3593072",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM (up to 5th-order masked)",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Recursive learning: neural network copies weights from lower-order model; breaks 5th-order masked Kyber with >99% probability",
	},
	{
		Title:        "DeePar-SCA: Breaking Parallel Architectures of Lattice Cryptography via Learning Based Side-Channel Attacks",
		Authors:      "Aydin, F., Kashyap, P., Potluri, S., Franzon, P., Aysu, A.",
		Year:         2020,
		Venue:        "SAMOS 2020",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-030-60939-9_18",
		Category:     "Side-Channel Attack",
		Algorithm:    "FrodoKEM + NewHope",
		FPGA:         "FPGA (hardware)",
		Contribution: "First deep-learning single-trace SCA on parallel FPGA lattice implementations; outperforms horizontal DPA by 900%",
	},
	{
		Title:        "Fault-Injection Attacks Against NIST's Post-Quantum Cryptography Round 3 KEM Candidates",
		Authors:      "Xagawa, K., Ito, A., Ueno, R., Takahashi, J., Homma, N.",
		Year:         2021,
		Venue:        "ASIACRYPT 2021",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-030-92075-3_2",
		Category:     "Side-Channel Attack",
		Algorithm:    "All NIST Round 3 KEMs",
		FPGA:         "ARM Cortex-M4 (validation)",
		Contribution: "Systematic fault injection study on all NIST KEM candidates; targets FO re-encryption equality test",
	},
	{
		Title:        "Fault-Enabled Chosen-Ciphertext Attacks on Kyber",
		Authors:      "Hermelink, J., Pessl, P., Poppelmann, T.",
		Year:         2021,
		Venue:        "INDOCRYPT 2021",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-030-92518-5_15",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Combined fault + chosen-ciphertext: single-bit manipulation with fault correction bypasses CCA countermeasures",
	},
	{
		Title:        "Grafting Trees: A Fault Attack Against the SPHINCS Framework",
		Authors:      "Castelnovi, L., Martinelli, A., Prest, T.",
		Year:         2018,
		Venue:        "PQCrypto 2018",
		URL:          "https://link.springer.com/chapter/10.1007/978-3-319-79063-3_8",
		Category:     "Side-Channel Attack",
		Algorithm:    "SLH-DSA",
		FPGA:         "Generic",
		Contribution: "First fault attack on SPHINCS framework: single faulted hash enables universal signature forgery (stealthy attack)",
	},
	{
		Title:        "Cracking the Mask: SASCA Against Local-Masked NTT for CRYSTALS-Kyber",
		Authors:      "Carrera Rodriguez, R., Bruguier, F., Valea, E., Benoit, P.",
		Year:         2025,
		Venue:        "IACR Communications in Cryptology, Vol. 2, Issue 2",
		URL:          "https://cic.iacr.org/p/2/2/23",
		Category:     "Side-Channel Attack",
		Algorithm:    "ML-KEM (local-masked NTT)",
		FPGA:         "Artix-7 (FPGA) and 22nm FDSOI (ASIC)",
		Contribution: "SASCA via modified factor graphs on local-masked NTT; shows small mask counts per layer are insufficient",
	},

	// =========================================================================
	// Category 8: Side-Channel Defenses for PQC Hardware
	// =========================================================================

	{
		Title:        "Masking Kyber: First- and Higher-Order Implementations",
		Authors:      "Bos, J.W., Gourjon, M., Renes, J., Schneider, T., van Vredendaal, C.",
		Year:         2021,
		Venue:        "TCHES 2021(4), pp. 173-214",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/9064",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM",
		FPGA:         "ARM Cortex-M4F",
		Contribution: "First completely masked (arbitrary-order) KEM; masked bit-sliced binary-search for compression; 3.5x first-order overhead",
	},
	{
		Title:        "First-Order Masked Kyber on ARM Cortex-M4",
		Authors:      "Heinz, D., Kannwischer, M.J., Land, G., Poppelmann, T., Schwabe, P., Sprenkels, A.",
		Year:         2022,
		Venue:        "ePrint 2022/058",
		URL:          "https://eprint.iacr.org/2022/058",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM",
		FPGA:         "ARM Cortex-M4",
		Contribution: "First liberally-licensed open-source masked Kyber; 2,978,441 cycles for Kyber768 decaps including RNG",
	},
	{
		Title:        "Masking Dilithium: Efficient Implementation and Side-Channel Evaluation",
		Authors:      "Migliore, V., Gerard, B., Tibouchi, M., Fouque, P.A.",
		Year:         2019,
		Venue:        "ACNS 2019, ePrint 2019/394",
		URL:          "https://eprint.iacr.org/2019/394",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-DSA",
		FPGA:         "ARM Cortex-M3",
		Contribution: "First masked Dilithium; power-of-two modulus variant makes masking 7.3-9x faster for critical operations",
	},
	{
		Title:        "Improved Gadgets for the High-Order Masking of Dilithium",
		Authors:      "Coron, J.S., Gerard, B., Trannoy, M., Zeitoun, R.",
		Year:         2023,
		Venue:        "TCHES 2023(4), pp. 110-145, ePrint 2023/896",
		URL:          "https://eprint.iacr.org/2023/896",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-DSA",
		FPGA:         "Generic (theoretical gadgets)",
		Contribution: "Novel ShiftMod gadget and B2A conversion with complexity independent of bit-width; proven secure in t-probing model",
	},
	{
		Title:        "Bitslicing Arithmetic/Boolean Masking Conversions for Fun and Profit",
		Authors:      "Bronchain, O., Cassiers, G.",
		Year:         2022,
		Venue:        "TCHES 2022(4), pp. 553-588",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/9831",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM + Saber",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Bitsliced arbitrary-order A2B/B2A conversion with up to 25x speedup; first arbitrary-order masked Kyber768",
	},
	{
		Title:        "Low-Cost Shuffling Countermeasures Against Side-Channel Attacks for NTT-Based Post-Quantum Cryptography",
		Authors:      "Fritzmann, T., Van Beirendonck, M., Basu Roy, D., Karl, P., Schamberger, T., Verbauwhede, I., Sigl, G.",
		Year:         2022,
		Venue:        "IEEE Trans. CAD",
		URL:          "https://ieeexplore.ieee.org/document/9772079/",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM + ML-DSA (NTT shuffling)",
		FPGA:         "FPGA / ASIC",
		Contribution: "Hardware shuffling converting nested NTT loops to single-level; randomized butterfly order with minimal area overhead",
	},
	{
		Title:        "A Hardware-Friendly Shuffling Countermeasure Against Side-Channel Attacks for Kyber",
		Authors:      "Xu, D., Long, J., Ma, T., Chen, D., Zheng, F., Cheung, R.C.C.",
		Year:         2024,
		Venue:        "arXiv 2407.02452",
		URL:          "https://arxiv.org/abs/2407.02452",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM",
		FPGA:         "FPGA",
		Contribution: "Coefficient index + NTT network randomization with unified shuffling controller; only 8.7% hardware efficiency loss",
	},
	{
		Title:        "Combined Fault and DPA Protection for Lattice-Based Cryptography",
		Authors:      "Heinz, D., Poppelmann, T.",
		Year:         2022,
		Venue:        "IEEE Trans. Computers, ePrint 2021/101",
		URL:          "https://eprint.iacr.org/2021/101",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Redundant number representation for SCA + CRT-based fault countermeasure; outperforms masking + redundant computation",
	},
	{
		Title:        "Adapting Belief Propagation to Counter Shuffling of NTTs",
		Authors:      "Hermelink, J., Streit, S., Strieder, E., Thieme, K.",
		Year:         2023,
		Venue:        "TCHES 2023(1), pp. 60-88",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/9947",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM (NTT shuffling evaluation)",
		FPGA:         "ARM Cortex-M4",
		Contribution: "Shuffle node for belief propagation learns permutation; shows NTT shuffling alone may be insufficient vs profiled single-trace",
	},
	{
		Title:        "Lightweight Fault Detection Architecture for NTT on FPGA",
		Authors:      "2025 authors",
		Year:         2025,
		Venue:        "arXiv 2508.03062",
		URL:          "https://arxiv.org/abs/2508.03062",
		Category:     "Side-Channel Defense",
		Algorithm:    "ML-KEM + ML-DSA + FALCON (NTT fault detection)",
		FPGA:         "FPGA",
		Contribution: "Memory Rule Checker for address-level integrity during NTT; first approach targeting address-level faults; 99.97% detection",
	},
	{
		Title:        "TVLA*: Test Vector Leakage Assessment on Hardware Implementations of Asymmetric Cryptography",
		Authors:      "Jayasena, A., Andrews, E., Mishra, P.",
		Year:         2023,
		Venue:        "IEEE Trans. VLSI Systems",
		URL:          "https://ieeexplore.ieee.org/document/10196024/",
		Category:     "Side-Channel Defense",
		Algorithm:    "Multi (TVLA methodology)",
		FPGA:         "FPGA",
		Contribution: "Extends TVLA to asymmetric/PQC with test generation for max power difference; 99.999% statistical confidence",
	},

	// =========================================================================
	// Category 9: Side-Channel Surveys
	// =========================================================================

	{
		Title:        "Side-channel and Fault-injection attacks over Lattice-based Post-quantum Schemes: Survey and New Results",
		Authors:      "Ravi, P., Chattopadhyay, A., D'Anvers, J.P., Bhasin, S.",
		Year:         2023,
		Venue:        "ACM Trans. Embedded Computing Systems (TECS)",
		URL:          "https://dl.acm.org/doi/10.1145/3603170",
		Category:     "SCA Survey",
		Algorithm:    "ML-KEM + ML-DSA (comprehensive)",
		FPGA:         "Multiple (MCU, FPGA)",
		Contribution: "Systematic survey of all SCA/FIA on Kyber and Dilithium; customized countermeasures for simultaneous protection",
	},
	{
		Title:        "SoK: Reassessing Side-Channel Vulnerabilities and Countermeasures in PQC Implementations",
		Authors:      "Dobias, P., Rezaeezade, A., Chmielewski, L., Malina, L., Batina, L.",
		Year:         2025,
		Venue:        "ePrint 2025/1222",
		URL:          "https://eprint.iacr.org/2025/1222",
		Category:     "SCA Survey",
		Algorithm:    "All PQC families",
		FPGA:         "Hardware (FPGA, ASIC) focus",
		Contribution: "Categorizes attacks from adversarial perspective; reviews hardware countermeasure efficacy; identifies unexplored surfaces",
	},

	// =========================================================================
	// Category 10: Code-Based / Other PQC Hardware
	// =========================================================================

	{
		Title:        "Hardware Implementations of BIKE",
		Authors:      "Richter-Brockmann, J., Mono, J., Guneysu, T.",
		Year:         2022,
		Venue:        "CHES 2022 / TCHES",
		URL:          "https://tches.iacr.org/",
		Category:     "Other PQC Hardware",
		Algorithm:    "BIKE",
		FPGA:         "FPGA",
		Contribution: "First efficient FPGA implementations of BIKE (QC-MDPC decoding) with constant-time guarantees",
	},
	{
		Title:        "FrodoKEM: Hardware Design of a Post-Quantum Key Encapsulation Mechanism",
		Authors:      "Howe, J., Oder, T., Krausz, M., Guneysu, T.",
		Year:         2021,
		Venue:        "IEEE TVLSI / ePrint",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "Other PQC Hardware",
		Algorithm:    "FrodoKEM",
		FPGA:         "FPGA",
		Contribution: "Standard LWE (no NTT) FPGA implementation; competitive via matrix multiplication optimization; higher area than Kyber",
	},
	{
		Title:        "Classic McEliece on FPGA",
		Authors:      "Kuo, P.C., Schneider, M. et al.",
		Year:         2023,
		Venue:        "PQCrypto / ePrint",
		URL:          "https://eprint.iacr.org/",
		Category:     "Other PQC Hardware",
		Algorithm:    "Classic McEliece",
		FPGA:         "High-end FPGA",
		Contribution: "Tackles ~1MB public keys through memory hierarchy optimizations; demonstrated feasibility on high-end FPGAs",
	},
	{
		Title:        "Hardware Accelerator for SIKE (Supersingular Isogeny Key Encapsulation)",
		Authors:      "Koziel, B., Azarderakhsh, R., Mozaffari-Kermani, M.",
		Year:         2021,
		Venue:        "IEEE Trans. Computers / CHES",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "Other PQC Hardware",
		Algorithm:    "SIKE (broken 2022, historical)",
		FPGA:         "FPGA",
		Contribution: "SIKE/SIDH FPGA implementation; techniques for Fp2 arithmetic remain relevant for successor isogeny schemes",
	},
	{
		Title:        "FALCON Hardware Implementation: Fast Fourier Sampling on FPGA",
		Authors:      "Zhao, C., Gaj, K. et al.",
		Year:         2023,
		Venue:        "CHES / ePrint",
		URL:          "https://eprint.iacr.org/",
		Category:     "Other PQC Hardware",
		Algorithm:    "FALCON",
		FPGA:         "Artix-7",
		Contribution: "Tackles FALCON's hard signing problem (discrete Gaussian sampling over NTRU with floating-point FFT); significant area overhead vs Dilithium",
	},
	{
		Title:        "A Highly-Efficient Lattice-Based Post-Quantum Cryptography Processor for IoT Applications",
		Authors:      "Ye, W., Song, Z. et al.",
		Year:         2024,
		Venue:        "TCHES 2024(2)",
		URL:          "https://tches.iacr.org/index.php/TCHES/article/view/11423",
		Category:     "Other PQC Hardware",
		Algorithm:    "ML-KEM + ML-DSA (IoT ASIC)",
		FPGA:         "ASIC (200 MHz, 2.01 mW for Kyber-512)",
		Contribution: "Novel SIMD hardware for Kyber+Dilithium targeting IoT; 10x speedup over RISC-V, 5x over Cortex-M4 at 2mW",
	},

	// =========================================================================
	// Category 11: Frameworks, Surveys, Standards, Industry
	// =========================================================================

	{
		Title:        "A Survey on Hardware Implementations of Post-Quantum Cryptography",
		Authors:      "Xie, J., Yang, K.",
		Year:         2022,
		Venue:        "ePrint 2022/030 / IEEE Transactions",
		URL:          "https://eprint.iacr.org/",
		Category:     "Survey",
		Algorithm:    "All PQC families",
		FPGA:         "Multiple",
		Contribution: "Most comprehensive hardware survey: lattice, code, hash, multivariate PQC; categorized architectures and area/throughput comparison",
	},
	{
		Title:        "Status Report on the Third Round of the NIST Post-Quantum Cryptography Standardization Process",
		Authors:      "NIST (Alagic, G. et al.)",
		Year:         2022,
		Venue:        "NISTIR 8413",
		URL:          "https://csrc.nist.gov/publications/detail/nistir/8413/final",
		Category:     "Standards",
		Algorithm:    "All NIST finalists",
		FPGA:         "N/A",
		Contribution: "Official NIST selection rationale for Kyber, Dilithium, FALCON, SPHINCS+; hardware implementation considerations",
	},
	{
		Title:        "Fair and Comprehensive Benchmarking of Post-Quantum Cryptography on FPGAs",
		Authors:      "Beckwith, L., Nguyen, D.T., Gaj, K.",
		Year:         2022,
		Venue:        "CHES / TCHES",
		URL:          "https://tches.iacr.org/",
		Category:     "Framework",
		Algorithm:    "Multi (benchmarking methodology)",
		FPGA:         "Multiple",
		Contribution: "Established fair FPGA benchmarking methodology for PQC: consistent devices, tool versions, interface conventions",
	},
	{
		Title:        "pqm4: Testing and Benchmarking NIST PQC on ARM Cortex-M4",
		Authors:      "Kannwischer, M.J., Rijneveld, J., Schwabe, P., Stoffelen, K.",
		Year:         2019,
		Venue:        "NIST PQC Conference",
		URL:          "https://github.com/mupq/pqm4",
		Category:     "Framework",
		Algorithm:    "All NIST candidates",
		FPGA:         "ARM Cortex-M4 (embedded benchmark)",
		Contribution: "Canonical benchmarking framework for PQC on embedded platforms; established methodology for fair comparison",
		RepoURL:      "https://github.com/mupq/pqm4",
	},
	{
		Title:        "Benchmarking Post-Quantum Cryptography in TLS",
		Authors:      "Paquin, C., Stebila, D., Tamvada, G.",
		Year:         2020,
		Venue:        "PQCrypto 2020",
		URL:          "https://eprint.iacr.org/",
		Category:     "Framework",
		Algorithm:    "Multi (TLS benchmark)",
		FPGA:         "Software",
		Contribution: "Systematic PQC benchmarking in TLS 1.3; provided baseline performance data motivating hardware acceleration",
	},
	{
		Title:        "A Reconfigurable Crypto-Processor for Post-Quantum Lattice-Based Protocols",
		Authors:      "Banerjee, U., Pathak, S., Chandrakasan, A.P.",
		Year:         2019,
		Venue:        "ISSCC 2019",
		URL:          "https://ieeexplore.ieee.org/",
		Category:     "Industry",
		Algorithm:    "ML-KEM (multi-scheme)",
		FPGA:         "28nm ASIC",
		Contribution: "First silicon PQC lattice crypto-processor; 12x energy improvement over Cortex-M4 software",
	},
	{
		Title:        "NIST FIPS 203 (ML-KEM), FIPS 204 (ML-DSA), FIPS 205 (SLH-DSA)",
		Authors:      "NIST",
		Year:         2024,
		Venue:        "NIST Federal Information Processing Standards",
		URL:          "https://csrc.nist.gov/publications/detail/fips/203/final",
		Category:     "Standards",
		Algorithm:    "ML-KEM + ML-DSA + SLH-DSA",
		FPGA:         "N/A",
		Contribution: "Final PQC standards; hardware implementations must conform for FIPS 140-3 validation",
	},
	{
		Title:        "Migration to Post-Quantum Cryptography",
		Authors:      "NIST NCCoE (Barker, W., Polk, W., Souppaya, M.)",
		Year:         2024,
		Venue:        "NIST SP 1800-38",
		URL:          "https://www.nccoe.nist.gov/crypto-agility-considerations-migrating-post-quantum-cryptographic-algorithms",
		Category:     "Standards",
		Algorithm:    "All PQC",
		FPGA:         "N/A",
		Contribution: "Industry migration roadmap: crypto-agility, asset inventory, prioritization for PQC transition in hardware/software",
	},
}

// OpenSourceRepos lists actively maintained open-source PQC FPGA
// implementations that can serve as reference designs.
var OpenSourceRepos = []struct {
	Name       string
	URL        string
	Algorithms string
	Language   string
	Notes      string
}{
	{"GMUCERG/Dilithium", "https://github.com/GMUCERG/Dilithium", "ML-DSA (all levels)", "Verilog", "Most cited; basis for ML-DSA-OSH"},
	{"KULeuven-COSIC/ML-DSA-OSH", "https://github.com/KULeuven-COSIC/ML-DSA-OSH", "ML-DSA (FIPS 204)", "RTL", "First open-source FIPS 204 compliant implementation"},
	{"slh-dsa/sloth", "https://github.com/slh-dsa/sloth", "SLH-DSA (all 12 param sets)", "Verilog + RISC-V C", "CRYPTO 2024 artifact"},
	{"caslab-code/pqc-hw-sphincslet", "https://github.com/caslab-code/pqc-hw-sphincslet", "SLH-DSA (area-efficient)", "RTL", "2025 IACR artifact"},
	{"bsc-loca/PQC-Crystals-HLS-Accelerators", "https://github.com/bsc-loca/PQC-Crystals-HLS-Accelerators", "ML-KEM + ML-DSA", "HLS C++", "Barcelona Supercomputing Center"},
	{"CityUHK-CALAS/SW-HW-Co-design-of-Dilithium", "https://github.com/CityUHK-CALAS/SW-HW-Co-design-of-Dilithium", "ML-DSA (Zynq co-design)", "Verilog + C", "Configurable, all security levels"},
	{"mupq/pqm4", "https://github.com/mupq/pqm4", "All NIST PQC (ARM Cortex-M4)", "C + ASM", "Canonical embedded PQC benchmark framework"},
	{"PQClean/PQClean", "https://github.com/PQClean/PQClean", "All NIST PQC (reference C)", "C", "Clean room reference implementations for HW verification"},
	{"pq-crystals/kyber", "https://github.com/pq-crystals/kyber", "ML-KEM (reference)", "C", "Official CRYSTALS-Kyber reference"},
}
